# THE RUSTIC TREES DEPENDENCY LIST & INFO
[package]
name = "rustic_trees"
version = "0.1.0"
edition = "2021"
authors = ["JustJazzFR jazzy.productions.incorporated@gmail.com"]
description = "Tree library (contianing Binary and N-ary trees) made in C and Rust"
license = "MIT"
repository = "https://github.com/JustJazzFR/rustic_trees"
keywords = ["ffi", "c", "tree", "binary", "n-ary"]
readme = "README.md"
categories = ["external-ffi-bindings", "data-structures"]

[build-dependencies]
cc = "1.0"
bindgen = "0.69"
